#!/usr/bin/env python3
"""Adds comprehensive real MTB destinations to bases.js"""
import re, shutil

SRC = "src/data/bases.js"
shutil.copy(SRC, SRC + ".pre-mtb")

with open(SRC, "r", encoding="utf-8") as f:
    src = f.read()

existing_names = set(re.findall(r'name:"([^"]+)"', src))
print(f"Existing destinations: {len(existing_names)}")

# All real global MTB destinations
MTB_HUBS = [
    # North America
    {"name":"Whistler Bike Park","country":"Canada","region":"British Columbia","lat":50.12,"lng":-122.95,"terrain":["MTB","bike park","downhill","enduro"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":4,"tags":["A-Line","world cup","Garbanzo","lift access","legendary","Creekside"],"ytQuery":"Whistler Mountain Bike Park A-Line trails","desc":"The world's most famous bike park with trails for every level. Base in Whistler Village.","why":"Every MTB rider's bucket list — A-Line, Garbanzo and endless lift-accessed trails","whyNot":"Expensive; very busy July-August; lift passes essential for DH riding"},
    {"name":"Squamish MTB","country":"Canada","region":"British Columbia","lat":49.70,"lng":-123.16,"terrain":["MTB","technical","enduro","natural"],"ability":[3,4,5],"months":[4,5,6,7,8,9,10],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":4,"tags":["technical","loam","roots","world class","natural trails","no lifts"],"ytQuery":"Squamish MTB trails British Columbia Canada","desc":"World-class natural trail network between Vancouver and Whistler. Base in Squamish.","why":"The finest natural MTB trail network in North America — loam, roots and rock perfection","whyNot":"Very technical; requires strong skills; wet season limits riding"},
    {"name":"Moab MTB","country":"USA","region":"Utah","lat":38.57,"lng":-109.55,"terrain":["MTB","slickrock","desert","enduro"],"ability":[3,4,5],"months":[3,4,5,10,11],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["slickrock","Whole Enchilada","Captain Ahab","desert","iconic","red rock"],"ytQuery":"Moab MTB trails Utah Whole Enchilada slickrock","desc":"Red rock MTB mecca with iconic slickrock and world-famous trail networks. Base in Moab town.","why":"Slickrock riding is unlike anything else on earth — the spiritual home of mountain biking","whyNot":"Extreme heat April-October; remote; technical skills essential; water scarce on trails"},
    {"name":"Bentonville MTB","country":"USA","region":"Arkansas","lat":36.37,"lng":-94.21,"terrain":["MTB","flow","enduro","XC","all levels"],"ability":[1,2,3,4,5],"months":[3,4,5,9,10,11],"rq":5,"tr":4,"ap":3,"kmh":[14,22],"climb_f":2,"tags":["Slaughter Pen","Crystal Bridges","flow trails","Walmart","fastest growing","world class"],"ytQuery":"Bentonville Arkansas MTB trails Slaughter Pen","desc":"The fastest-growing MTB destination in the world — purpose-built world-class trail network. Base in Bentonville.","why":"Walmart-funded world-class trails — the best value MTB destination in the USA right now","whyNot":"Summer heat and humidity brutal; best avoided July-August; still building infrastructure"},
    {"name":"Sedona MTB","country":"USA","region":"Arizona","lat":34.87,"lng":-111.76,"terrain":["MTB","slickrock","technical","scenic"],"ability":[2,3,4,5],"months":[2,3,4,5,10,11],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Hiline","Hangover","red rock","scenic","technical","world famous"],"ytQuery":"Sedona MTB Hiline Hangover trails Arizona","desc":"Red sandstone MTB in the most jaw-dropping landscape in the USA. Base in Sedona.","why":"The most visually stunning MTB on earth — Hiline and Hangover are genuinely extraordinary","whyNot":"Very technical; sharp rock punishes tires; extremely hot June-September"},
    {"name":"Crested Butte MTB","country":"USA","region":"Colorado","lat":38.87,"lng":-106.98,"terrain":["MTB","alpine","XC","enduro"],"ability":[3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":4,"tags":["birthplace of MTB","401 trail","alpine","wildflowers","high altitude","legendary"],"ytQuery":"Crested Butte MTB Colorado 401 trail alpine","desc":"Where mountain biking was born — epic alpine singletrack at altitude. Base in Crested Butte.","why":"The 401 Trail is the most celebrated XC route in the USA — alpine wildflowers and perfect singletrack","whyNot":"Very high altitude (9,000ft+); short season June-September; very remote"},
    {"name":"Pisgah MTB","country":"USA","region":"North Carolina","lat":35.34,"lng":-82.79,"terrain":["MTB","enduro","technical","roots"],"ability":[3,4,5],"months":[4,5,6,9,10,11],"rq":5,"tr":4,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Black Mountain","enduro world series","Appalachian","roots","EWS","waterfalls"],"ytQuery":"Pisgah MTB trails North Carolina Black Mountain","desc":"East Coast premier enduro destination in the Appalachian Mountains. Base in Brevard.","why":"Pisgah's rooty chunky trails are unlike anything else — East Coast riding at its absolute finest","whyNot":"Very technical; roots and rocks punishing; rain makes trails dangerous; long drives between trailheads"},
    {"name":"Kingdom Trails Vermont","country":"USA","region":"Vermont","lat":44.63,"lng":-72.02,"terrain":["MTB","XC","flow","community"],"ability":[1,2,3,4],"months":[5,6,7,8,9,10],"rq":4,"tr":3,"ap":4,"kmh":[14,22],"climb_f":2,"tags":["Northeast Kingdom","community trails","East Burke","New England","accessible","friendly"],"ytQuery":"Kingdom Trails Vermont MTB East Burke","desc":"New England's finest community trail network. Base in East Burke.","why":"The most welcoming MTB community in the USA — every ability level catered for beautifully","whyNot":"Mud season April-May; trails close when wet; limited accommodation"},
    {"name":"Copper Harbor MTB","country":"USA","region":"Michigan","lat":47.47,"lng":-87.89,"terrain":["MTB","enduro","loam","remote"],"ability":[3,4,5],"months":[6,7,8,9],"rq":4,"tr":4,"ap":5,"kmh":[12,20],"climb_f":2,"tags":["loam","remote","Upper Peninsula","hidden gem","world class","uncrowded"],"ytQuery":"Copper Harbor MTB Michigan trails loam","desc":"Remote Upper Peninsula MTB gem with world-class loam trails. Base in Copper Harbor.","why":"The most underrated MTB in the USA — perfect dark loam and virtually zero crowds","whyNot":"Extremely remote; very short season; limited accommodation; 8-hour drive from Chicago"},
    {"name":"Park City MTB","country":"USA","region":"Utah","lat":40.64,"lng":-111.50,"terrain":["MTB","alpine","enduro","lift access"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":4,"kmh":[12,22],"climb_f":4,"tags":["Mid Mountain","Wasatch","high altitude","lift access","USAC Pro","world class"],"ytQuery":"Park City MTB Utah Wasatch trails lift access","desc":"World-class lift-accessed MTB in an Olympic ski resort at 7,000ft. Base in Park City.","why":"Tour de France climbs converted to epic MTB — 400 miles of trails at altitude","whyNot":"Altitude sickness possible; expensive resort prices; short season"},
    {"name":"Downieville California","country":"USA","region":"California","lat":39.56,"lng":-120.83,"terrain":["MTB","downhill","enduro","epic descent"],"ability":[3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":4,"kmh":[10,18],"climb_f":5,"tags":["Downieville Downhill","legendary descent","Sierra Nevada","shuttle","classic","old school"],"ytQuery":"Downieville Downhill MTB California classic","desc":"The legendary 17-mile Downieville Downhill — the original classic shuttle descent. Base in Downieville.","why":"The Downieville Downhill created shuttle culture — still one of the world's great descents","whyNot":"Shuttle essential; remote; very technical; snow closes trail until June"},
    {"name":"Fruita Colorado","country":"USA","region":"Colorado","lat":39.16,"lng":-108.73,"terrain":["MTB","desert","singletrack","XC"],"ability":[2,3,4],"months":[3,4,5,10,11],"rq":4,"tr":4,"ap":4,"kmh":[14,22],"climb_f":2,"tags":["18 Road","Kokopelli","desert","red rock","Colorado","pump track"],"ytQuery":"Fruita Colorado MTB 18 Road trails","desc":"Desert singletrack mecca in western Colorado. Base in Fruita or Grand Junction.","why":"18 Road trails are world-class desert singletrack — Kokopelli Trail is legendary","whyNot":"Very hot in summer; remote; some trails require navigation skills"},
    {"name":"Bellingham Washington","country":"USA","region":"Washington","lat":48.75,"lng":-122.48,"terrain":["MTB","technical","enduro","Pacific Northwest"],"ability":[3,4,5],"months":[5,6,7,8,9],"rq":4,"tr":4,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Galbraith","Pacific Northwest","loam","technical","Chuckanut","world class"],"ytQuery":"Bellingham MTB Galbraith Mountain Washington trails","desc":"Pacific Northwest MTB at its finest on Galbraith Mountain. Base in Bellingham.","why":"Galbraith Mountain has 50+ miles of world-class natural trail — PNW riding perfection","whyNot":"Rain frequent October-April; very technical; limited in shoulder seasons"},
    {"name":"Durango MTB","country":"USA","region":"Colorado","lat":37.28,"lng":-107.88,"terrain":["MTB","alpine","enduro","XC"],"ability":[3,4,5],"months":[5,6,7,8,9],"rq":4,"tr":4,"ap":4,"kmh":[12,20],"climb_f":4,"tags":["Colorado Trail","Horse Gulch","Hermosa Creek","mountain town","pro training","altitude"],"ytQuery":"Durango Colorado MTB trails Colorado Trail","desc":"Mountain biking's spiritual home in the San Juan Mountains. Base in Durango.","why":"Colorado Trail access from town, Horse Gulch XC and Hermosa Creek epic — world class","whyNot":"High altitude; remote from major airports; short season; some trails very demanding"},
    # Europe
    {"name":"Finale Ligure MTB","country":"Italy","region":"Liguria","lat":44.17,"lng":8.34,"terrain":["MTB","enduro","DH","technical"],"ability":[3,4,5],"months":[4,5,6,9,10,11],"rq":5,"tr":5,"ap":3,"kmh":[12,20],"climb_f":4,"tags":["EWS","Enduro World Series","limestone","Italian","world cup","EWS venue"],"ytQuery":"Finale Ligure MTB enduro trails Italy EWS","desc":"Europe's enduro capital with limestone trails above the Ligurian coast. Base in Finale Ligure.","why":"Finale is Europe's MTB mecca — EWS venue with 200km of trails in perfect limestone","whyNot":"Gets busy in shoulder season; summer very hot; some trails require paid shuttle"},
    {"name":"Morzine MTB","country":"France","region":"Haute-Savoie","lat":46.17,"lng":6.71,"terrain":["MTB","bike park","enduro","alpine","lift access"],"ability":[2,3,4,5],"months":[6,7,8],"rq":5,"tr":5,"ap":3,"kmh":[12,22],"climb_f":4,"tags":["Portes du Soleil","600km trails","cross-border","lifts","enduro","largest MTB area"],"ytQuery":"Morzine MTB Portes du Soleil bike park France","desc":"The world's largest lift-accessed MTB area crossing France and Switzerland. Base in Morzine.","why":"600km of trails across two countries — the biggest lift-accessed MTB area on earth","whyNot":"Very expensive; extremely busy July-August; shuttle dependent for best trails"},
    {"name":"Innerleithen MTB","country":"UK","region":"Scotland","lat":55.62,"lng":-3.07,"terrain":["MTB","enduro","DH","technical"],"ability":[3,4,5],"months":[4,5,6,7,8,9],"rq":5,"tr":4,"ap":3,"kmh":[12,20],"climb_f":3,"tags":["EWS","Traquair","Minch Moor","world cup DH","enduro","7stanes"],"ytQuery":"Innerleithen MTB Scotland enduro downhill EWS","desc":"Scotland's premier enduro destination and World Cup DH venue. Base in Innerleithen.","why":"EWS and World Cup DH venue — Traquair and Minch Moor trails are among Europe's best","whyNot":"Rain very frequent; midges June-August; some trails extremely demanding"},
    {"name":"Verbier MTB","country":"Switzerland","region":"Valais","lat":46.10,"lng":7.22,"terrain":["MTB","enduro","alpine","high altitude","lift access"],"ability":[3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":3,"kmh":[12,20],"climb_f":5,"tags":["high alpine","EWS","lift access","3000m","Swiss Alps","technical"],"ytQuery":"Verbier MTB Switzerland enduro trails lift access","desc":"High alpine enduro in the world's most prestigious ski resort at 3000m. Base in Verbier.","why":"The most dramatic high-altitude MTB in Europe — trails at 3,000m with extraordinary views","whyNot":"Extremely expensive; very short season; altitude demanding; technically very challenging"},
    {"name":"Leogang MTB","country":"Austria","region":"Salzburg","lat":47.43,"lng":12.76,"terrain":["MTB","bike park","DH","enduro","lift access"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":5,"tr":4,"ap":3,"kmh":[12,22],"climb_f":3,"tags":["world cup DH","Saalbach","bike park","Austria","lift access","family friendly"],"ytQuery":"Leogang MTB bike park Austria world cup downhill","desc":"World Cup DH venue with bike park and enduro trails. Base in Leogang or Saalbach.","why":"World Cup DH on your doorstep — excellent bike park with trails for all levels","whyNot":"Short season; expensive Austrian resort prices; DH lift queues in peak season"},
    {"name":"Sölden MTB","country":"Austria","region":"Tyrol","lat":46.97,"lng":11.00,"terrain":["MTB","bike park","enduro","high alpine"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":4,"tr":4,"ap":3,"kmh":[12,22],"climb_f":4,"tags":["Bike Republic","Ötztaler","high alpine","lift access","Austria","enduro"],"ytQuery":"Solden MTB Bike Republic Austria enduro","desc":"Ötztal's bike republic with high alpine trails at 3,000m. Base in Sölden.","why":"Extraordinary high altitude bike park in the Ötztal — 40+ trails from beginner to expert","whyNot":"Very short season; expensive; altitude sickness possible; weather extreme"},
    {"name":"Glentress MTB","country":"UK","region":"Scotland","lat":55.65,"lng":-3.19,"terrain":["MTB","enduro","XC","flow","7stanes"],"ability":[1,2,3,4,5],"months":[3,4,5,6,7,8,9,10],"rq":4,"tr":3,"ap":3,"kmh":[12,22],"climb_f":2,"tags":["7stanes","Peebles","all levels","world class","XC","Scotland"],"ytQuery":"Glentress MTB Scotland 7stanes trails","desc":"Scotland's busiest and best MTB centre in the 7Stanes network. Base in Peebles.","why":"Best value MTB in the UK — world-class trails for all levels in stunning Scottish forest","whyNot":"Rain frequent; midges in summer; busy at weekends; some black trails very demanding"},
    {"name":"Afan Forest MTB","country":"UK","region":"Wales","lat":51.63,"lng":-3.71,"terrain":["MTB","enduro","XC","Wales"],"ability":[2,3,4,5],"months":[3,4,5,6,7,8,9,10],"rq":4,"tr":3,"ap":3,"kmh":[12,22],"climb_f":3,"tags":["W2","The Wall","Skyline","Wales","all levels","purpose built"],"ytQuery":"Afan Forest MTB Wales trails enduro","desc":"Wales's premier MTB destination with world-class purpose-built trails. Base in Port Talbot.","why":"W2 and Skyline are world-class enduro trails — Wales punches well above its weight","whyNot":"Rain very frequent; can be muddy; trails close when waterlogged"},
    {"name":"Finale Ligure","country":"Italy","region":"Liguria","lat":44.17,"lng":8.34,"terrain":["MTB","enduro","limestone","sea views"],"ability":[2,3,4,5],"months":[4,5,6,9,10,11],"rq":5,"tr":5,"ap":3,"kmh":[12,20],"climb_f":4,"tags":["Finale","EWS","enduro","limestone","world cup","Italian coast"],"ytQuery":"Finale Ligure enduro MTB trails Italy","desc":"Mediterranean enduro capital — limestone trails from mountains to sea. Base in Finale Ligure.","why":"200km of world-class trails ending at the Mediterranean — the perfect MTB destination","whyNot":"Very popular; expensive during EWS; summer heat; some trails require shuttles"},
    {"name":"La Thuile MTB","country":"Italy","region":"Aosta Valley","lat":45.72,"lng":6.97,"terrain":["MTB","enduro","alpine","lift access"],"ability":[3,4,5],"months":[6,7,8,9],"rq":4,"tr":5,"ap":3,"kmh":[12,20],"climb_f":5,"tags":["Bike World","Aosta Valley","enduro","France border","lift access","alpine"],"ytQuery":"La Thuile MTB Bike World enduro Italy","desc":"Cross-border alpine enduro in the Aosta Valley. Base in La Thuile.","why":"Dramatic alpine enduro with lift access and cross-border trails into France","whyNot":"Very short season; expensive; requires lift passes; weather extreme at altitude"},
    {"name":"Lenzerheide MTB","country":"Switzerland","region":"Graubünden","lat":46.73,"lng":9.56,"terrain":["MTB","bike park","world cup","enduro"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":5,"tr":5,"ap":3,"kmh":[12,22],"climb_f":4,"tags":["world cup XCO","world cup DH","Bike Kingdom","lift access","Switzerland","world class"],"ytQuery":"Lenzerheide MTB Bike Kingdom Switzerland world cup","desc":"World Cup XCO and DH venue in Switzerland's Bike Kingdom. Base in Lenzerheide.","why":"Both World Cup XCO and DH on the same mountain — extraordinary Swiss trail quality","whyNot":"Expensive Swiss resort prices; very busy during World Cup events; short season"},
    {"name":"Kirchberg Kitzbühel MTB","country":"Austria","region":"Tyrol","lat":47.45,"lng":12.46,"terrain":["MTB","enduro","alpine","EWS"],"ability":[3,4,5],"months":[6,7,8,9],"rq":4,"tr":4,"ap":3,"kmh":[12,20],"climb_f":4,"tags":["EWS venue","Kitzbühel","enduro","Austrian Alps","lift access","legendary"],"ytQuery":"Kirchberg Kitzbühel MTB Austria EWS enduro","desc":"EWS venue in one of the Alps' most famous ski resorts. Base in Kirchberg or Kitzbühel.","why":"EWS-quality enduro trails in an iconic Austrian resort — facilities are world class","whyNot":"Very expensive; short season; altitude takes adjustment"},
    # Australasia
    {"name":"Blue Derby MTB","country":"Australia","region":"Tasmania","lat":-41.19,"lng":147.86,"terrain":["MTB","enduro","technical","Tasmania"],"ability":[2,3,4,5],"months":[10,11,12,1,2,3,4],"rq":5,"tr":5,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Ozzy Ozzy Ozzy","Blue Tier","world class","enduro","Tasmania","unique"],"ytQuery":"Blue Derby MTB Tasmania trails enduro","desc":"World-class enduro trails in Tasmania's forest. Base in Derby.","why":"Australia's finest MTB destination — Ozzy Ozzy Ozzy and Blue Tier are world-class","whyNot":"Remote; ferry or flight to Tasmania; limited accommodation in Derby; leeches in wet season"},
    {"name":"Rotorua MTB","country":"New Zealand","region":"North Island","lat":-38.14,"lng":176.25,"terrain":["MTB","XC","enduro","Redwoods"],"ability":[1,2,3,4,5],"months":[1,2,3,4,5,6,7,8,9,10,11,12],"rq":5,"tr":4,"ap":4,"kmh":[12,22],"climb_f":2,"tags":["Redwoods","world cup XCO","Whakarewarewa","year round","geothermal","world class"],"ytQuery":"Rotorua MTB Redwoods New Zealand trails world cup","desc":"Year-round world-class MTB in the geothermal Redwoods forest. Base in Rotorua.","why":"The best year-round MTB in the southern hemisphere — Redwoods and geothermal combine perfectly","whyNot":"Sulphur smell takes getting used to; town can feel touristy; some trails very muddy after rain"},
    {"name":"Queenstown MTB","country":"New Zealand","region":"South Island","lat":-45.03,"lng":168.66,"terrain":["MTB","enduro","bike park","alpine"],"ability":[2,3,4,5],"months":[10,11,12,1,2,3,4,5],"rq":5,"tr":5,"ap":4,"kmh":[12,22],"climb_f":4,"tags":["Skyline","Coronet Peak","enduro","adventure capital","lift access","spectacular"],"ytQuery":"Queenstown MTB Skyline Coronet Peak New Zealand","desc":"Adventure capital of the world with world-class MTB. Base in Queenstown.","why":"Gondola access to Skyline trails with Remarkables views — NZ MTB at its finest","whyNot":"Expensive NZ resort prices; summer very crowded; winter closes many trails"},
    {"name":"Maydena Bike Park","country":"Australia","region":"Tasmania","lat":-42.78,"lng":146.61,"terrain":["MTB","bike park","DH","enduro","lift access"],"ability":[2,3,4,5],"months":[10,11,12,1,2,3,4],"rq":5,"tr":5,"ap":4,"kmh":[10,18],"climb_f":4,"tags":["Australia's best DH","lift access","ancient forest","world class","unique","huon pine"],"ytQuery":"Maydena Bike Park Tasmania downhill MTB","desc":"Australia's premier lift-accessed bike park in ancient Huon Pine forest. Base in Maydena.","why":"Australia's best DH bike park in world's oldest living forest — completely unique","whyNot":"Remote; ferry or flight to Tasmania; very short bike park season; expensive lift passes"},
    {"name":"Stromlo MTB","country":"Australia","region":"ACT","lat":-35.33,"lng":148.99,"terrain":["MTB","XC","flow","pump track"],"ability":[1,2,3,4],"months":[3,4,5,9,10,11],"rq":4,"tr":3,"ap":3,"kmh":[14,22],"climb_f":2,"tags":["Canberra","world cup XCO","purpose built","flow trails","pump track","accessible"],"ytQuery":"Stromlo Forest Park MTB Canberra Australia trails","desc":"World Cup XCO venue in Canberra with purpose-built trails. Base in Canberra.","why":"World Cup on your doorstep — brilliant purpose-built trails for all levels near the capital","whyNot":"Summer very hot; limited natural terrain; best for XC rather than enduro"},
    # Asia
    {"name":"Chiang Mai MTB","country":"Thailand","region":"North Thailand","lat":18.79,"lng":98.98,"terrain":["MTB","jungle","enduro","XC"],"ability":[2,3,4],"months":[11,12,1,2,3],"rq":3,"tr":3,"ap":4,"kmh":[12,20],"climb_f":2,"tags":["Doi Suthep","jungle","Chiang Mai","tropical","affordable","adventure"],"ytQuery":"Chiang Mai MTB trails Thailand Doi Suthep jungle","desc":"Tropical jungle MTB on Doi Suthep above Thailand's most beautiful city. Base in Chiang Mai.","why":"Unique tropical MTB experience — jungle trails above a stunning ancient city","whyNot":"Very hot March-October; roads busy near city; bikes and equipment limited quality"},
    {"name":"Hakuba MTB","country":"Japan","region":"Nagano","lat":36.70,"lng":137.86,"terrain":["MTB","bike park","alpine","Japan"],"ability":[2,3,4,5],"months":[6,7,8,9],"rq":4,"tr":4,"ap":4,"kmh":[12,22],"climb_f":3,"tags":["Olympic resort","gondola","Japanese Alps","lift access","unique","EWS"],"ytQuery":"Hakuba MTB bike park Japan gondola Alpine","desc":"Japan's premier lift-accessed MTB destination in the Olympic resort. Base in Hakuba.","why":"World-class lift-accessed MTB with uniquely Japanese culture — extraordinary experience","whyNot":"Short season; expensive Japan prices; limited English at some facilities; very busy in peak"},
    {"name":"Jeju Island MTB","country":"South Korea","region":"Jeju","lat":33.49,"lng":126.53,"terrain":["MTB","coastal","volcanic","XC"],"ability":[1,2,3,4],"months":[4,5,6,9,10],"rq":3,"tr":3,"ap":4,"kmh":[14,22],"climb_f":2,"tags":["Hallasan","volcanic","cycling island","unique","coastal","Korea"],"ytQuery":"Jeju Island MTB mountain bike trails Korea volcanic","desc":"Volcanic island MTB with world-class infrastructure. Base in Jeju City.","why":"Unique volcanic island MTB — well signed, excellent roads, extraordinary scenery","whyNot":"Summer monsoon; very crowded in peak season; limited challenging terrain on coast"},
    # Africa
    {"name":"Jonkershoek MTB","country":"South Africa","region":"Western Cape","lat":-33.95,"lng":18.94,"terrain":["MTB","enduro","fynbos","technical"],"ability":[3,4,5],"months":[4,5,6,7,8,9,10],"rq":4,"tr":4,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Stellenbosch","Cape Epic","fynbos","enduro","wine country","world class"],"ytQuery":"Jonkershoek MTB Stellenbosch South Africa trails","desc":"World-class MTB in the fynbos above Stellenbosch. Base in Stellenbosch.","why":"Cape Epic terrain on your doorstep with wine farm recoveries — South Africa's finest MTB","whyNot":"Summer very hot; some trails close in fire season; baboons on trails"},
    {"name":"Tokai Forest MTB","country":"South Africa","region":"Western Cape","lat":-34.05,"lng":18.42,"terrain":["MTB","forest","technical","Cape Town"],"ability":[2,3,4,5],"months":[4,5,6,7,8,9,10],"rq":4,"tr":3,"ap":4,"kmh":[12,20],"climb_f":2,"tags":["Cape Town","Table Mountain","pine forest","Xterra","accessible","urban trail"],"ytQuery":"Tokai Forest MTB Cape Town South Africa trails","desc":"Mountain biking in the shadow of Table Mountain. Base in Cape Town southern suburbs.","why":"World-class trails minutes from Cape Town — unique urban-fringe MTB experience","whyNot":"Fire season trail closures; some areas security awareness needed; wind can be extreme"},
    # South America
    {"name":"Bariloche MTB","country":"Argentina","region":"Río Negro","lat":-41.14,"lng":-71.31,"terrain":["MTB","enduro","lakes","alpine"],"ability":[2,3,4,5],"months":[11,12,1,2,3],"rq":4,"tr":4,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Nahuel Huapi","Patagonia","lakes","enduro","chocolate","Cerro Catedral"],"ytQuery":"Bariloche MTB trails Argentina Patagonia Cerro Catedral","desc":"Patagonian MTB among lakes and mountains. Base in Bariloche.","why":"Extraordinary alpine MTB in Patagonia with chocolate and lake views as reward","whyNot":"Wind can be extreme; trails rough in places; short summer season; remote"},
    {"name":"Medellín MTB","country":"Colombia","region":"Antioquia","lat":6.25,"lng":-75.57,"terrain":["MTB","enduro","tropical","altitude"],"ability":[2,3,4,5],"months":[12,1,2,6,7,8],"rq":3,"tr":3,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Colombian cycling","altitude","tropical","affordable","emerging","enduro"],"ytQuery":"Medellin MTB Colombia trails enduro","desc":"Emerging world-class MTB destination in Colombia's cycling heartland. Base in Medellín.","why":"Outstanding mountain trails at great altitude near a transformed, vibrant city","whyNot":"Security awareness needed; some roads rough; infrastructure still developing"},
    {"name":"Pucon MTB","country":"Chile","region":"Los Lagos","lat":-39.28,"lng":-71.98,"terrain":["MTB","volcanic","enduro","technical"],"ability":[2,3,4,5],"months":[11,12,1,2,3],"rq":4,"tr":4,"ap":4,"kmh":[12,20],"climb_f":3,"tags":["Villarrica volcano","lake district","enduro","technical","unique","adventure"],"ytQuery":"Pucon MTB Chile volcano trails enduro","desc":"Volcanic MTB around an active volcano in the Chilean Lake District. Base in Pucón.","why":"Cycling around an active volcano with lake views — completely unique experience","whyNot":"Rain frequent; roads rough in places; short season; remote from major airports"},
]

# Filter out already existing
new_hubs = [d for d in MTB_HUBS if d['name'] not in existing_names]
print(f"New MTB hubs to add: {len(new_hubs)}")

# Convert to JS and append to bases.js
def to_js(v):
    if isinstance(v, str):
        return f'"{v.replace(chr(92), chr(92)*2).replace(chr(34), chr(92)+chr(34))}"'
    elif isinstance(v, list):
        return "[" + ",".join(to_js(i) for i in v) + "]"
    elif isinstance(v, bool):
        return "true" if v else "false"
    elif isinstance(v, (int, float)):
        return str(v)
    return f'"{v}"'

def dest_to_js(d):
    return "{" + ",".join(f'{k}:{to_js(v)}' for k, v in d.items()) + "}"

js_entries = ",\n".join(dest_to_js(d) for d in new_hubs)

# Insert before closing ]; of BASES array
close_idx = src.rfind("];")
insert_at = close_idx
while insert_at > 0 and src[insert_at-1] in (' ', '\t', '\n', '\r'):
    insert_at -= 1

new_src = src[:insert_at] + ",\n" + js_entries + "\n" + src[insert_at:]

with open(SRC, "w", encoding="utf-8") as f:
    f.write(new_src)

total = len(re.findall(r'name:"', new_src))
print(f"Done! Total destinations: {total}")
print(f"Run: npm run dev")
