#!/usr/bin/env python3
"""
Robust i18n key insertion — finds each language block by opener,
walks to its closing brace, inserts keys just before it.
"""
import re, shutil, os

SRC = "src/App.jsx"
shutil.copy(SRC, SRC + ".pre-i18n2")

with open(SRC, "r", encoding="utf-8") as f:
    src = f.read()

def find_lang_block_end(src, lang_code):
    """Find the position just before the closing }, of a language block."""
    # Find the lang opener e.g. \nen:{ or ,en:{
    pat = re.compile(r'[\n,]\s*' + re.escape(lang_code) + r'\s*:\s*\{')
    m = pat.search(src)
    if not m:
        return None
    
    # Walk from the opening { counting depth
    start = m.end() - 1  # position of {
    depth = 0
    i = start
    in_str = False
    str_ch = None
    
    while i < len(src):
        c = src[i]
        if in_str:
            if c == '\\':
                i += 2
                continue
            if c == str_ch:
                in_str = False
        else:
            if c in ('"', "'", '`'):
                in_str = True
                str_ch = c
            elif c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    return i  # position of closing }
        i += 1
    return None

LANGS = ["en", "nl", "pt", "pl", "cs", "da", "sv", "no", "ja", "zh"]

NEW_KEYS = {
    "en": {"whyMatched":"WHY MATCHED","aboutDest":"ABOUT THIS DESTINATION","furtherReading":"FURTHER READING","routesRiding":"ROUTES AND RIDING","exploreStrava":"Explore on Strava","browseKomoot":"Browse on Komoot","whereToStay":"WHERE TO STAY","whyCyclists":"WHY CYCLISTS STAY HERE","bikeShopsNearby":"BIKE SHOPS AND HIRE","yourDailyPlan":"YOUR DAILY PLAN","routeMap":"ROUTE MAP","bestAreaStay":"BEST AREA TO STAY","pricesApprox":"prices approx, verify before booking","viewHotelBtn":"View hotel","selfCateringOpt":"SELF-CATERING OPTION","outAndBack":"OUT-AND-BACK","directions":"DIRECTIONS FROM BASE","insiderTips":"INSIDER TIPS","recommendedBase":"RECOMMENDED BASE HOTEL","moreRidesFrom":"MORE RIDES FROM","otherRoutes":"OTHER CLASSIC ROUTES","videoSection":"VIDEO INSPIRATION","watchYoutube":"Watch on YouTube","whatToRide":"WHAT TO RIDE","foodFuel":"FOOD AND FUEL","whereStay":"WHERE TO STAY","alsoExplore":"ALSO EXPLORE","planYourTrip":"Get matched hotels, routes and local intel - free","notQuiteRight":"Not quite right?","shareWithFriend":"Share this trip","sendToFriend":"SEND TO A FRIEND","postOnSocial":"POST ON SOCIAL","groupTrip":"Going with a group?","groupComingSoon":"Group mode coming soon","primaryAirport":"PRIMARY AIRPORT","altAirport":"ALTERNATIVE AIRPORT","bikeTransport":"BIKE TRANSPORT","localKnowledge":"LOCAL INSIDER KNOWLEDGE","whatCouldGoWrong":"WHAT COULD GO WRONG","preRide":"PRE-RIDE","midRide":"MID-RIDE","postRide":"POST-RIDE","localFuel":"LOCAL FUEL","setAsBase":"Set as my base","day":"Day","estTime":"Est. time","difficulty":"Difficulty","distance":"Distance","elevation":"Elevation","style":"Style","baseTown":"Base town"},
    "nl": {"whyMatched":"WAAROM GEMATCHT","aboutDest":"OVER DEZE BESTEMMING","furtherReading":"MEER LEZEN","routesRiding":"ROUTES EN RIJDEN","exploreStrava":"Verkennen op Strava","browseKomoot":"Bekijken op Komoot","whereToStay":"WAAR TE VERBLIJVEN","whyCyclists":"WAAROM FIETSERS HIER BLIJVEN","bikeShopsNearby":"FIETSWINKELS EN VERHUUR","yourDailyPlan":"UW DAGELIJKSE PLANNING","routeMap":"ROUTEKAART","bestAreaStay":"BESTE VERBLIJFSGEBIED","pricesApprox":"indicatieve prijzen, verifieer voor boeking","viewHotelBtn":"Hotel bekijken","selfCateringOpt":"ZELFVERZORGING OPTIE","outAndBack":"HEEN EN TERUG","directions":"AANWIJZINGEN VANAF BASIS","insiderTips":"INSIDER TIPS","recommendedBase":"AANBEVOLEN BASISHOTEL","moreRidesFrom":"MEER RITTEN VANUIT","otherRoutes":"ANDERE KLASSIEKE ROUTES","videoSection":"VIDEO INSPIRATIE","watchYoutube":"Bekijk op YouTube","whatToRide":"WAT TE RIJDEN","foodFuel":"ETEN EN BRANDSTOF","whereStay":"WAAR TE VERBLIJVEN","alsoExplore":"OOK ONTDEKKEN","planYourTrip":"Krijg matched hotels en routes - gratis","notQuiteRight":"Niet helemaal goed?","shareWithFriend":"Deel deze trip","sendToFriend":"STUUR NAAR EEN VRIEND","postOnSocial":"DEEL OP SOCIALE MEDIA","groupTrip":"Met een groep?","groupComingSoon":"Groepsmodus binnenkort","primaryAirport":"PRIMAIRE LUCHTHAVEN","altAirport":"ALTERNATIEVE LUCHTHAVEN","bikeTransport":"FIETSTRANSPORT","localKnowledge":"LOKALE INSIDER KENNIS","whatCouldGoWrong":"WAT KAN ER MISGAAN","preRide":"VOOR DE RIT","midRide":"TIJDENS DE RIT","postRide":"NA DE RIT","localFuel":"LOKALE BRANDSTOF","setAsBase":"Instellen als basis","day":"Dag","estTime":"Geschatte tijd","difficulty":"Moeilijkheid","distance":"Afstand","elevation":"Hoogteverschil","style":"Stijl","baseTown":"Basisstad"},
    "pt": {"whyMatched":"PORQUE CORRESPONDIDO","aboutDest":"SOBRE ESTE DESTINO","furtherReading":"LEITURA ADICIONAL","routesRiding":"ROTAS E CICLISMO","exploreStrava":"Explorar no Strava","browseKomoot":"Ver no Komoot","whereToStay":"ONDE FICAR","whyCyclists":"PORQUE OS CICLISTAS FICAM AQUI","bikeShopsNearby":"LOJAS E ALUGUER","yourDailyPlan":"PLANO DIARIO","routeMap":"MAPA DE ROTA","bestAreaStay":"MELHOR AREA","pricesApprox":"precos aproximados, verifique antes","viewHotelBtn":"Ver hotel","selfCateringOpt":"ALOJAMENTO PROPRIO","outAndBack":"IDA E VOLTA","directions":"DIRECOES DA BASE","insiderTips":"DICAS DE INSIDER","recommendedBase":"HOTEL BASE RECOMENDADO","moreRidesFrom":"MAIS PERCURSOS DE","otherRoutes":"OUTRAS ROTAS","videoSection":"INSPIRACAO EM VIDEO","watchYoutube":"Ver no YouTube","whatToRide":"O QUE PEDALAR","foodFuel":"COMIDA E COMBUSTIVEL","whereStay":"ONDE FICAR","alsoExplore":"TAMBEM EXPLORAR","planYourTrip":"Obtenha hoteis e rotas - gratis","notQuiteRight":"Nao esta bem?","shareWithFriend":"Partilhe esta viagem","sendToFriend":"ENVIAR A UM AMIGO","postOnSocial":"PUBLICAR NAS REDES","groupTrip":"Com um grupo?","groupComingSoon":"Modo grupo em breve","primaryAirport":"AEROPORTO PRINCIPAL","altAirport":"AEROPORTO ALTERNATIVO","bikeTransport":"TRANSPORTE DE BICICLETA","localKnowledge":"CONHECIMENTO LOCAL","whatCouldGoWrong":"O QUE PODE CORRER MAL","preRide":"PRE-PEDALADA","midRide":"A MEIO","postRide":"POS-PEDALADA","localFuel":"COMBUSTIVEL LOCAL","setAsBase":"Definir como base","day":"Dia","estTime":"Tempo estimado","difficulty":"Dificuldade","distance":"Distancia","elevation":"Elevacao","style":"Estilo","baseTown":"Cidade base"},
    "pl": {"whyMatched":"DLACZEGO DOPASOWANO","aboutDest":"O TEJ DESTYNACJI","furtherReading":"DALSZA LEKTURA","routesRiding":"TRASY I JAZDA","exploreStrava":"Eksploruj na Stravie","browseKomoot":"Przegladaj na Komoot","whereToStay":"GDZIE NOCOWAC","whyCyclists":"DLACZEGO KOLARZE TU NOCUJA","bikeShopsNearby":"SKLEPY I WYPOZYCZALNIE","yourDailyPlan":"TWOJ DZIENNY PLAN","routeMap":"MAPA TRASY","bestAreaStay":"NAJLEPSZA OKOLICA","pricesApprox":"ceny przyblizne, zweryfikuj przed rezerwacja","viewHotelBtn":"Zobacz hotel","selfCateringOpt":"OPCJA SAMODZIELNA","outAndBack":"TAM I Z POWROTEM","directions":"WSKAZOWKI OD BAZY","insiderTips":"PORADY INSIDEROW","recommendedBase":"POLECANY HOTEL BAZOWY","moreRidesFrom":"WIECEJ TRAS Z","otherRoutes":"INNE KLASYCZNE TRASY","videoSection":"INSPIRACJA WIDEO","watchYoutube":"Ogladaj na YouTube","whatToRide":"CO JEZDZIC","foodFuel":"JEDZENIE I PALIWO","whereStay":"GDZIE NOCOWAC","alsoExplore":"ODKRYJ ROWNIEZ","planYourTrip":"Dopasowane hotele i trasy - bezplatnie","notQuiteRight":"Nie do konca?","shareWithFriend":"Podziel sie trasa","sendToFriend":"WYSLIJ DO PRZYJACIELA","postOnSocial":"OPUBLIKUJ W MEDIACH","groupTrip":"Z grupa?","groupComingSoon":"Tryb grupowy wkrotce","primaryAirport":"GLOWNE LOTNISKO","altAirport":"ALTERNATYWNE LOTNISKO","bikeTransport":"TRANSPORT ROWERU","localKnowledge":"LOKALNA WIEDZA","whatCouldGoWrong":"CO MOZE POJSC ZLE","preRide":"PRZED JAZDA","midRide":"W TRAKCIE","postRide":"PO JEZDZIE","localFuel":"LOKALNE PALIWO","setAsBase":"Ustaw jako baze","day":"Dzien","estTime":"Szacowany czas","difficulty":"Trudnosc","distance":"Dystans","elevation":"Przewyzszenie","style":"Styl","baseTown":"Miasto bazowe"},
    "cs": {"whyMatched":"PROC SPAROVANO","aboutDest":"O TOMTO MISTE","furtherReading":"DALSI CTENI","routesRiding":"TRASY A JIZDA","exploreStrava":"Prozkoumat na Strave","browseKomoot":"Prochazet na Komoot","whereToStay":"KDE POBYVAT","whyCyclists":"PROC TU CYKLISTE ZUSTAVAJI","bikeShopsNearby":"OBCHODY A PUJCOVNY","yourDailyPlan":"VAS DENNI PLAN","routeMap":"MAPA TRASY","bestAreaStay":"NEJLEPSI OBLAST","pricesApprox":"priblizne ceny, overuji pred rezervaci","viewHotelBtn":"Zobrazit hotel","selfCateringOpt":"VLASTNI STRAVOVANI","outAndBack":"TAM A ZPET","directions":"POKYNY OD ZAKLADNY","insiderTips":"TIPY INSIDERU","recommendedBase":"DOPORUCENY HOTEL","moreRidesFrom":"VICE JIZD Z","otherRoutes":"JINE KLASICKE TRASY","videoSection":"VIDEO INSPIRACE","watchYoutube":"Sledovat na YouTube","whatToRide":"CO JEZDIT","foodFuel":"JIDLO A PALIVO","whereStay":"KDE POBYVAT","alsoExplore":"TAKE PROZKOUMAT","planYourTrip":"Ziskejte hotely a trasy - zdarma","notQuiteRight":"Neni to ono?","shareWithFriend":"Sdilejte vylet","sendToFriend":"POSLAT PRITELI","postOnSocial":"ZVEREJNIT NA SITI","groupTrip":"Se skupinou?","groupComingSoon":"Skupinovy rezim brzy","primaryAirport":"HLAVNI LETISTE","altAirport":"ALTERNATIVNI LETISTE","bikeTransport":"TRANSPORT KOLA","localKnowledge":"MISTNI ZNALOSTI","whatCouldGoWrong":"CO MUZE JIT SPATNE","preRide":"PRED JIZDOU","midRide":"BEHEM JIZDY","postRide":"PO JIZDE","localFuel":"MISTNI PALIVO","setAsBase":"Nastavit jako zakladnu","day":"Den","estTime":"Odhadovany cas","difficulty":"Obtiznost","distance":"Vzdalenost","elevation":"Prevyseni","style":"Styl","baseTown":"Zakladni mesto"},
    "da": {"whyMatched":"HVORFOR MATCHET","aboutDest":"OM DENNE DESTINATION","furtherReading":"VIDERE LAESNING","routesRiding":"RUTER OG CYKLING","exploreStrava":"Udforsk pa Strava","browseKomoot":"Gennemse pa Komoot","whereToStay":"HVOR MAN BOR","whyCyclists":"HVORFOR CYKLISTER BOR HER","bikeShopsNearby":"CYKELFORRETNINGER","yourDailyPlan":"DIN DAGLIGE PLAN","routeMap":"RUTEKORT","bestAreaStay":"BEDSTE OMRADE","pricesApprox":"omtrentlige priser, tjek for booking","viewHotelBtn":"Se hotel","selfCateringOpt":"SELVFORPLEJNING","outAndBack":"TUR-RETUR","directions":"VEJLEDNING FRA BASE","insiderTips":"INSIDER TIPS","recommendedBase":"ANBEFALET BASISHOTEL","moreRidesFrom":"FLERE TURE FRA","otherRoutes":"ANDRE KLASSISKE RUTER","videoSection":"VIDEO INSPIRATION","watchYoutube":"Se pa YouTube","whatToRide":"HVAD MAN CYKLER","foodFuel":"MAD OG BRAENDSTOF","whereStay":"HVOR MAN BOR","alsoExplore":"UDFORSK OGSA","planYourTrip":"Fa matchede hoteller og ruter - gratis","notQuiteRight":"Ikke helt rigtigt?","shareWithFriend":"Del denne tur","sendToFriend":"SEND TIL EN VEN","postOnSocial":"POST PA SOCIALE MEDIER","groupTrip":"Med en gruppe?","groupComingSoon":"Gruppetistand kommer snart","primaryAirport":"PRIMAER LUFTHAVN","altAirport":"ALTERNATIV LUFTHAVN","bikeTransport":"CYKELTRANSPORT","localKnowledge":"LOKAL INSIDERVIDEN","whatCouldGoWrong":"HVAD KAN GA GALT","preRide":"FOR TUREN","midRide":"UNDER TUREN","postRide":"EFTER TUREN","localFuel":"LOKALT BRAENDSTOF","setAsBase":"Angiv som min base","day":"Dag","estTime":"Estimeret tid","difficulty":"Svaerhedsgrad","distance":"Afstand","elevation":"Stigning","style":"Stil","baseTown":"Baseby"},
    "sv": {"whyMatched":"VARFOR MATCHAD","aboutDest":"OM DENNA DESTINATION","furtherReading":"VIDARE LASNING","routesRiding":"RUTTER OCH CYKLING","exploreStrava":"Utforska pa Strava","browseKomoot":"Bladdra pa Komoot","whereToStay":"VAR MAN BOR","whyCyclists":"VARFOR CYKLISTER STANNAR HAR","bikeShopsNearby":"CYKELAFFARER","yourDailyPlan":"DIN DAGLIGA PLAN","routeMap":"RUTTKARTA","bestAreaStay":"BASTA OMRADET","pricesApprox":"ungefaerliga priser, kontrollera innan bokning","viewHotelBtn":"Visa hotell","selfCateringOpt":"SJALVHUSHALLNING","outAndBack":"FRAM OCH TILLBAKA","directions":"VAGBESKRIVNING","insiderTips":"INSIDERTIPS","recommendedBase":"REKOMMENDERAT HOTELL","moreRidesFrom":"FLER TURER FRAN","otherRoutes":"ANDRA KLASSISKA RUTTER","videoSection":"VIDEOINSPIRATION","watchYoutube":"Titta pa YouTube","whatToRide":"VAD MAN CYKLAR","foodFuel":"MAT OCH BRAENSLE","whereStay":"VAR MAN BOR","alsoExplore":"UTFORSKA OCKSA","planYourTrip":"Fa matchade hotell och rutter - gratis","notQuiteRight":"Inte riktigt ratt?","shareWithFriend":"Dela resan","sendToFriend":"SKICKA TILL EN VAN","postOnSocial":"POSTA PA SOCIALA MEDIER","groupTrip":"Med en grupp?","groupComingSoon":"Grupplade kommer snart","primaryAirport":"PRIMAER FLYGPLATS","altAirport":"ALTERNATIV FLYGPLATS","bikeTransport":"CYKELTRANSPORT","localKnowledge":"LOKAL INSIDERKUNSKAP","whatCouldGoWrong":"VAD KAN GA FEL","preRide":"FORE TUREN","midRide":"UNDER TUREN","postRide":"EFTER TUREN","localFuel":"LOKALT BRAENSLE","setAsBase":"Ange som min bas","day":"Dag","estTime":"Beraeknad tid","difficulty":"Svarighetsgrad","distance":"Avstand","elevation":"Hojdmeter","style":"Stil","baseTown":"Basstad"},
    "no": {"whyMatched":"HVORFOR MATCHET","aboutDest":"OM DENNE DESTINASJONEN","furtherReading":"VIDERE LESING","routesRiding":"RUTER OG SYKLING","exploreStrava":"Utforsk pa Strava","browseKomoot":"Bla pa Komoot","whereToStay":"HVOR MAN BOR","whyCyclists":"HVORFOR SYKLISTER BOR HER","bikeShopsNearby":"SYKKELBUTIKKER","yourDailyPlan":"DIN DAGLIGE PLAN","routeMap":"RUTEKART","bestAreaStay":"BESTE OMRADE","pricesApprox":"omtrentlige priser, sjekk for booking","viewHotelBtn":"Se hotell","selfCateringOpt":"SELVFORSYNING","outAndBack":"TUR-RETUR","directions":"VEIBESKRIVELSE","insiderTips":"INSIDER TIPS","recommendedBase":"ANBEFALT BASISHOTELL","moreRidesFrom":"FLERE TURER FRA","otherRoutes":"ANDRE KLASSISKE RUTER","videoSection":"VIDEOINSPIRASON","watchYoutube":"Se pa YouTube","whatToRide":"HVA MAN SYKLER","foodFuel":"MAT OG DRIVSTOFF","whereStay":"HVOR MAN BOR","alsoExplore":"UTFORSK OGSA","planYourTrip":"Fa matchede hoteller og ruter - gratis","notQuiteRight":"Ikke helt riktig?","shareWithFriend":"Del turen","sendToFriend":"SEND TIL EN VENN","postOnSocial":"POST PA SOSIALE MEDIER","groupTrip":"Med en gruppe?","groupComingSoon":"Gruppemodus kommer snart","primaryAirport":"PRIMAER FLYPLASS","altAirport":"ALTERNATIV FLYPLASS","bikeTransport":"SYKKELTRANSPORT","localKnowledge":"LOKAL INSIDERKUNNSKAP","whatCouldGoWrong":"HVA KAN GA GALT","preRide":"FOR TUREN","midRide":"UNDER TUREN","postRide":"ETTER TUREN","localFuel":"LOKALT DRIVSTOFF","setAsBase":"Sett som min base","day":"Dag","estTime":"Estimert tid","difficulty":"Vanskelighetsgrad","distance":"Avstand","elevation":"Stigning","style":"Stil","baseTown":"Baseby"},
    "ja": {"whyMatched":"マッチした理由","aboutDest":"この目的地について","furtherReading":"さらに読む","routesRiding":"ルートとライド","exploreStrava":"Stravaで探索","browseKomoot":"Komootで閲覧","whereToStay":"宿泊場所","whyCyclists":"サイクリストがここに泊まる理由","bikeShopsNearby":"自転車店とレンタル","yourDailyPlan":"日程","routeMap":"ルートマップ","bestAreaStay":"最適な宿泊エリア","pricesApprox":"概算価格、予約前に確認","viewHotelBtn":"ホテルを見る","selfCateringOpt":"自炊オプション","outAndBack":"往復","directions":"基地からの道順","insiderTips":"インサイダーのヒント","recommendedBase":"おすすめ拠点ホテル","moreRidesFrom":"こちらのルート","otherRoutes":"その他の定番ルート","videoSection":"動画インスピレーション","watchYoutube":"YouTubeで見る","whatToRide":"走るルート","foodFuel":"食事と補給","whereStay":"宿泊場所","alsoExplore":"こちらも探索","planYourTrip":"マッチしたホテルとルートを取得 - 無料","notQuiteRight":"少し違いますか？","shareWithFriend":"友達にシェア","sendToFriend":"友達に送る","postOnSocial":"SNSに投稿","groupTrip":"グループでお出かけですか？","groupComingSoon":"グループモード近日公開","primaryAirport":"主要空港","altAirport":"代替空港","bikeTransport":"自転車輸送","localKnowledge":"地元の情報","whatCouldGoWrong":"注意点","preRide":"ライド前","midRide":"ライド中","postRide":"ライド後","localFuel":"現地補給食","setAsBase":"拠点に設定","day":"日","estTime":"推定時間","difficulty":"難易度","distance":"距離","elevation":"獲得標高","style":"スタイル","baseTown":"拠点の町"},
    "zh": {"whyMatched":"为何匹配","aboutDest":"关于此目的地","furtherReading":"延伸阅读","routesRiding":"路线与骑行","exploreStrava":"在Strava探索","browseKomoot":"在Komoot浏览","whereToStay":"住宿地点","whyCyclists":"为何骑行者选择这里","bikeShopsNearby":"自行车店与租赁","yourDailyPlan":"每日计划","routeMap":"路线地图","bestAreaStay":"最佳住宿区域","pricesApprox":"参考价格，预订前请核实","viewHotelBtn":"查看酒店","selfCateringOpt":"自助住宿选项","outAndBack":"往返路线","directions":"从基地出发方向","insiderTips":"内部人士建议","recommendedBase":"推荐基地酒店","moreRidesFrom":"更多路线","otherRoutes":"其他经典骑行路线","videoSection":"视频灵感","watchYoutube":"在YouTube观看","whatToRide":"骑行路线","foodFuel":"饮食与补给","whereStay":"住宿地点","alsoExplore":"也可探索","planYourTrip":"获取匹配酒店和路线 - 免费","notQuiteRight":"不太合适？","shareWithFriend":"分享此行程","sendToFriend":"发送给朋友","postOnSocial":"发布到社交媒体","groupTrip":"与团队一起旅行？","groupComingSoon":"团队模式即将推出","primaryAirport":"主要机场","altAirport":"备用机场","bikeTransport":"自行车运输","localKnowledge":"本地信息","whatCouldGoWrong":"注意事项","preRide":"骑行前","midRide":"骑行中","postRide":"骑行后","localFuel":"当地补给","setAsBase":"设为基地","day":"天","estTime":"预计时间","difficulty":"难度","distance":"距离","elevation":"爬升","style":"风格","baseTown":"基地城镇"},
}

inserted = 0
for lang in LANGS:
    end_pos = find_lang_block_end(src, lang)
    if end_pos is None:
        print(f"  ⚠  {lang}: block not found")
        continue
    
    keys = NEW_KEYS.get(lang, {})
    # Build comma-separated key:value string
    key_str = "," + ",".join(f'{k}:"{v}"' for k, v in keys.items())
    
    # Insert before the closing }
    src = src[:end_pos] + key_str + src[end_pos:]
    print(f"  ✓  {lang}: {len(keys)} keys added")
    inserted += 1

with open(SRC, "w", encoding="utf-8") as f:
    f.write(src)

print(f"\n✅ Done — {inserted} languages updated")
print("Run: npm run dev")
